### ISSUE TITLE
SimpleDemo Execution Exception

### ISSUE THREAD

**Issue by ingted** [akkadotnet/Akka.Hosting#179]
Version of Akka.NET? Which Akka.NET Modules? clone Akka.Hosting and executed Build.cmd

```

[INFO][1/3/2023 5:31:47 AM][Thread 0001][remoting (akka://MyActorSystem)] Starting remoting
[INFO][1/3/2023 5:31:47 AM][Thread 0001][remoting (akka://MyActorSystem)] Remoting started; listening on addresses : [akka.tcp://MyActorSystem@localhost:8110]
[INFO][1/3/2023 5:31:47 AM][Thread 0001][remoting (akka://MyActorSystem)] Remoting now listens on addresses: [akka.tcp://MyActorSystem@localhost:8110]
[INFO][1/3/2023 5:31:47 AM][Thread 0001][Cluster (akka://MyActorSystem)] Cluster Node [akka.tcp://MyActorSystem@localhost:8110] - Starting up...
[INFO][1/3/2023 5:31:47 AM][Thread 0001][Cluster (akka://MyActorSystem)] Cluster Node [akka.tcp://MyActorSystem@localhost:8110] - Started up successfully
[INFO][1/3/2023 5:31:47 AM][Thread 0005][Cluster (akka://MyActorSystem)] Cluster Node [0.4.0] - Node [akka.tcp://MyActorSystem@localhost:8110] is JOINING itself (with roles [], version [0.4.0]) and forming a new cluster
[INFO][1/3/2023 5:31:47 AM][Thread 0005][Cluster (akka://MyActorSystem)] Cluster Node [akka.tcp://MyActorSystem@localhost:8110] - is the new leader among reachable nodes (more leaders may exist)
[INFO][1/3/2023 5:31:47 AM][Thread 0005][Cluster (akka://MyActorSystem)] Cluster Node [akka.tcp://MyActorSystem@localhost:8110] - Leader is moving node [akka.tcp://MyActorSystem@localhost:8110] to [Up]
[INFO][1/3/2023 5:31:47 AM][Thread 0015][akka.tcp://MyActorSystem@localhost:8110/system/sharding/myRegion] myRegion: Idle entities will be passivated after [00:02:00]
[INFO][1/3/2023 5:31:48 AM][Thread 0013][akka.tcp://MyActorSystem@localhost:8110/system/sharding/myRegionCoordinator] Singleton manager started singleton actor [akka://MyActorSystem/system/sharding/myRegionCoordinator/singleton]
[INFO][1/3/2023 5:31:48 AM][Thread 0013][akka.tcp://MyActorSystem@localhost:8110/system/sharding/myRegionCoordinator] ClusterSingletonManager state change [Start -> Oldest] Akka.Cluster.Tools.Singleton.Uninitialized
[INFO][1/3/2023 5:31:48 AM][Thread 0003][akka.tcp://MyActorSystem@localhost:8110/system/sharding/myRegionCoordinator/singleton/coordinator] Sharding Coordinator was moved to the active state Akka.Cluster.Sharding.PersistentShardCoordinator+State
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:61877
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:61878
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: G:\git\Akka.Hosting\src\Examples\Akka.Hosting.SimpleDemo\
[ERROR][1/3/2023 5:31:49 AM][Thread 0013][akka://MyActorSystem/system/sharding/myRegion/3/0HMND9F7KSI93%3A00000001] Error while creating actor instance of type Akka.Hosting.SimpleDemo.EchoActor with 0 args: ()
Cause: [akka://MyActorSystem/system/sharding/myRegion/3/0HMND9F7KSI93%3A00000001#345915985]: Akka.Actor.ActorInitializationException: Exception during creation
 ---> System.TypeLoadException: Error while creating actor instance of type Akka.Hosting.SimpleDemo.EchoActor with 0 args: ()
 ---> System.InvalidOperationException: Cannot resolve scoped service 'Akka.Hosting.SimpleDemo.IReplyGenerator' from root provider.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Akka.DependencyInjection.ServiceProviderActorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass116_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
[INFO][1/3/2023 5:31:49 AM][Thread 0003][akka://MyActorSystem/system/sharding/myRegion/3/0HMND9F7KSI93%3A00000001] Message [String] from [akka://MyActorSystem/temp/g] to [akka://MyActorSystem/system/sharding/myRegion/3/0HMND9F7KSI93%3A00000001#345915985] was not delivered. [1] dead letters encountered. If this is not an expected behavior then [akka://MyActorSystem/system/sharding/myRegion/3/0HMND9F7KSI93%3A00000001#345915985] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

```

Clone -> Build -> Set Akka.Hosting.SimpleDemo as startup project. -> F5

A clear and concise description of what you expected to happen. -> There should be no exceptions?!

Are you running on Linux? Windows? Docker? Which version of .NET? => Windows 2019, .net 7.101

**Comment by ingted** [comment]
It seems like the service tries\ to create the actor without parameter entityId and replyGenerator...

**Comment by ingted** [comment]
Workaround:
Change

```
return s => resolver.Props<EchoActor>(s);
```

To

```
return s => resolver.Props<EchoActor>(new object[] { s, new DefaultReplyGenerator() });
```

**Comment by Arkatufus** [comment]
@ingted 
I could not reproduce this, are you running the simple demo from the latest dev branch?

**Comment by ingted** [comment]
are you running the simple demo from the latest dev branch => yes

**Comment by Arkatufus** [comment]
Can you make sure that you rebuild the solution first? We did a dependency injection update a few weeks ago and that might have broken the sample.

**Comment by ingted** [comment]
![image](https://user-images.githubusercontent.com/4289161/210641447-fdb476c7-072d-4828-9114-b38e294b12e8.png)
![image](https://user-images.githubusercontent.com/4289161/210641588-7e754ea3-4cd6-4fca-91b1-2a0fbfe64b7f.png)

I think so...

Actually you can see
```
public EchoActor(string entityId, IReplyGenerator replyGenerator)
```
It take 2 parameters however the invocation only feed 1
```
return s => resolver.Props<EchoActor>(s);
```

**Comment by ingted** [comment]
![image](https://user-images.githubusercontent.com/4289161/210642022-5dfc5db6-e644-4453-a7ed-c879ba537249.png)

**Comment by Arkatufus** [comment]
It is supposed to be like that, actually. `IReplyGenerator` is supposed to be injected automatically by the dependency injection. We'll investigate further, thank you for the report.

**Comment by Arkatufus** [comment]
@ingted  
I've managed to reproduce your error by commenting the service registration code, the clue is in the exception message:
```
Unable to resolve service for type 'Akka.Hosting.SimpleDemo.IReplyGenerator' while attempting to activate 'Akka.Hosting.SimpleDemo.EchoActor'
```

Can you make sure that the line `builder.Services.AddScoped<IReplyGenerator, DefaultReplyGenerator>();` exists in your code?

**Comment by ingted** [comment]
I think so... (didn't change the cloned repo)

![image](https://user-images.githubusercontent.com/4289161/210728973-75ffec07-a206-42c7-9769-f8a4790f92f3.png)

**Comment by ingted** [comment]
https://user-images.githubusercontent.com/4289161/210730288-53f46f36-3b1c-47aa-8356-c51f1d58d6ee.mp4

Hi @Arkatufus ,

I recorded my screen and you can take a look at it...

**Comment by Arkatufus** [comment]
Hmmm... that is really weird, I'll try and look into it again today. Thanks!

**Comment by Aaronontheweb** [comment]
I've tested the following environments in order to reproduce this:

* VS2022 ❌ 
* `dotnet run -c Release` ✔️ 
* JetBrains Rider 2022.3 (IIS) ✔️ 
* JetBrains Rider 2022.3 (Kestrel / Self-host) ❌

**Comment by Aaronontheweb** [comment]
Actually, I'm not sure if this is Kestrel vs. IIS thing in Rider:

![image](https://user-images.githubusercontent.com/326939/210809865-3033c63b-a037-48a6-8856-6dd1c38b7793.png)

Why does the top profile fail but the other succeeds?

**Comment by Arkatufus** [comment]
This is a bit weird, but when you set "ASPNETCORE_ENVIRONMENT" to "Production", the sample code works just fine.
Here's the content of my `launchSettings.json`
```json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:50409",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Production"
      }
    },
    "Akka.Hosting.SimpleDemo": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Production"
      },
      "applicationUrl": "https://localhost:5001;http://localhost:5000"
    }
  }
}
```

**Comment by Aaronontheweb** [comment]
Got an answer as to why this works sometimes but not others:

https://twitter.com/chton/status/1611051567892905986?s=20&t=-8TUuAd9GD2oZcFmZyxY1w

**Comment by ingted** [comment]
Wow!!! After reading all your discurrion... Got it now!!! @@a
