### ISSUE TITLE
builder.AddSetup(DependencyResolverSetup.Create(provider)) not apply

### ISSUE THREAD

**Issue by powerumc** [akkadotnet/Akka.Hosting#393]
**Version Information**
Version of Akka.NET? 1.5.13
Which Akka.NET Modules? Akka.Hosting

**Describe the bug**
The code did not work, so I reviewed the akka.hosting code.
https://github.com/akkadotnet/Akka.Hosting/blob/dev/src/Akka.Hosting/AkkaConfigurationBuilder.cs#L142-L146

```cs
             // don't apply the diSetup
             if (setup is DependencyResolverSetup)
             {
                 return this;
             }
```

I was hoping that the DependencyResolverSetup setting would work correctly.
Is there a reason why this code doesn't do anything?

**To Reproduce**
My Code.
```cs
        services.AddAkka(appConfig.Name, (builder, provider) =>
        {
            var config = ConfigurationFactory.ParseString(@"...");
            builder.AddHocon(config, HoconAddMode.Prepend)
                .AddSetup(DependencyResolverSetup.Create(provider));
            // skip
```

_Links to working reproductions on Github / Gitlab are very much appreciated_

**Expected behavior**
I expected 

**Caller**
```cs
[ApiController]
public class TestController
{
    private readonly IServiceProvider _sp;
    private readonly ActorSystem _system;

    public TestController(ActorSystem system,
        IServiceProvider sp)
    {
        _system = system;
        _sp = sp;
    }

    [HttpGet("/test")]
    public async Task<string> Test()
    {
        var address = Address.Parse("akka.tcp://...@localhost:5011");
        var props = EchoActor.Props(_system)
            .WithDeploy(new Deploy(new RemoteScope(address)));
        var actorRef = _system.ActorOf(props);
        var str = await actorRef.Ask<Response>(new Request("HELLO"));

        return str.Message;
    }
}

```

Callee
```cs
public class EchoActor : ReceiveActor
{
    private readonly IServiceProvider _sp;
    private readonly ILoggingAdapter _logger = Context.GetLogger();
    
    public EchoActor(IServiceProvider sp)
    {
        _sp = sp;
        Receive<Request>(OnReceiveEcho);
    }

    public static Props Props(ActorSystem actorSystem)
    {
        var props = DependencyResolver.For(actorSystem).Props<EchoActor>();
        return props;
    }
```

**Actual behavior**
What actually happened and how did it differ from your expectations?
```
[ERROR][10/29/2023 17:15:20.566Z][Thread 0021][akka.tcp://...@localhost:5011/remote/akka.tcp/r...@localhost:5001/user/$b] Error while creating actor instance of type ....AspNetCore.Actors.EchoActor with 0 args: ()
Cause: [akka.tcp://...@localhost:5011/remote/akka.tcp/...@localhost:5001/user/$b#270112165]: Akka.Actor.ActorInitializationException: Exception during creation
 ---> System.TypeLoadException: Error while creating actor instance of type ....AspNetCore.Actors.EchoActor with 0 args: ()
 ---> System.MissingMethodException: Constructor on type '....AspNetCore.Actors.EchoActor' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass116_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)

```

**Screenshots**

**Environment**
Are you running on Linux? Windows? Docker? Which version of .NET?
.NET 7

**Additional context**

**Comment by Aaronontheweb** [comment]
thanks @powerumc - we will look into this

**Comment by Arkatufus** [comment]
can you include the source code for `EchoActor`, especially the constructor.

**Comment by Arkatufus** [comment]
@powerumc 

Since `Akka.Hosting` is tightly coupled to `Microsoft.Extensions.Hosting`, this functionality needs to be delegated to the hosting infrastructure. This can be quite daunting to do because the `IServiceProvider` itself is not coded in a friendly way. A good discussion for this can be found [here](https://stackoverflow.com/questions/50480082/use-custom-iserviceprovider-implementation-in-asp-net-core).
