### ISSUE TITLE
WithLoggerFactory unable to load logger

### ISSUE THREAD

**Issue by cecilphillip** [akkadotnet/Akka.Hosting#78]
**Version Information**
Akka 1.4.39
Akka.hosting 0.4.0

**Describe the bug**
Using `WithLoggerFactory` throws Akka.Configuration.ConfigurationException:

**To Reproduce**
Create a new console application using the dotnet cli
```
> dotnet new console
```

Install dependencies
```xml
    <ItemGroup>
      <PackageReference Include="Akka" Version="1.4.39" />
      <PackageReference Include="Akka.Hosting" Version="0.4.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.0.0" />
    </ItemGroup>
```
Update program.cs
```csharp
using var host = CreateHostBuilder(args)
    .UseConsoleLifetime().Build();

await host.StartAsync();

var actorSystem = host.Services.GetRequiredService<ActorSystem>();

Console.ReadLine();

await actorSystem.Terminate();
await actorSystem.WhenTerminated;
await host.StopAsync();

static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureServices(services =>
        {
            services.AddAkka("AkkaSandbox", (configBuilder, provider) =>
            {
                configBuilder.AddHocon("akka.loglevel = DEBUG")
                    .WithLoggerFactory();
            });
        });
```

Error message
```
crit: Akka.Hosting.AkkaHostedService[0]
      Unable to start AkkaHostedService - shutting down application
Akka.Configuration.ConfigurationException: Logger [Akka.Hosting.Logging.LoggerFactoryLogger, Akka.Hosting] specified in config cannot be loaded: System.AggregateException: One or more errors occurred. (Timeout after 00:00:05 seconds)
 ---> Akka.Actor.AskTimeoutException: Timeout after 00:00:05 seconds
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.Event.LoggingBus.AddLogger(ActorSystemImpl system, Type loggerType, LogLevel logLevel, String loggingBusName, TimeSpan timeout)
   at Akka.Event.LoggingBus.StartDefaultLoggers(ActorSystemImpl system)
 ---> System.AggregateException: One or more errors occurred. (Timeout after 00:00:05 seconds)
 ---> Akka.Actor.AskTimeoutException: Timeout after 00:00:05 seconds
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.Event.LoggingBus.AddLogger(ActorSystemImpl system, Type loggerType, LogLevel logLevel, String loggingBusName, TimeSpan timeout)
   at Akka.Event.LoggingBus.StartDefaultLoggers(ActorSystemImpl system)
   --- End of inner exception stack trace ---
   at Akka.Event.LoggingBus.StartDefaultLoggers(ActorSystemImpl system)
   at Akka.Actor.LocalActorRefProvider.Init(ActorSystemImpl system)
   at Akka.Actor.Internal.ActorSystemImpl.Start()
   at Akka.Actor.ActorSystem.CreateAndStartSystem(String name, Config withFallback, ActorSystemSetup setup)
   at Akka.Actor.ActorSystem.Create(String name, ActorSystemSetup setup)
   at Akka.Hosting.AkkaConfigurationBuilder.<>c.<ActorSystemFactory>b__28_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Akka.Hosting.AkkaHostedService.StartAsync(CancellationToken cancellationToken)

```

**Environment**
MacOS Monetery, .NET 6

**Comment by Arkatufus** [comment]
@cecilphillip We think we know what is causing this to happen, we'll make a patch as soon as possible

**Comment by Arkatufus** [comment]
@cecilphillip I've made a fix PR, waiting for @Aaronontheweb review
